In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests

In [2]:
url = 'https://www.imdb.com/search/title/?genres=Thriller&sort=user_rating,desc&title_type=feature&num_votes=25000,&ref_=chtmvm_gnr_20'

response = requests.get(url)

print(response)

<Response [200]>

In [3]:
import re

In [4]:
from bs4 import BeautifulSoup

In [5]:
soup = BeautifulSoup(response.text,'html.parser')

In [6]:
listings = soup.find('div',class_='lister-list').find_all('div',class_='lister-item mode-advanced')

print(len(listings))

50

In [38]:
thiller_movie_list = []
for movie in listings:
  index = movie.find('h3').find('span',class_='lister-item-index unbold text-primary').get_text().split('.')[0]
  movie_name = movie.find('h3').a.text
  rating = movie.find('div',class_='ratings-bar').strong.text.split('.')[0]
  story = movie.find('p').findNext('p').get_text(strip=True)
  director = movie.find('p').findNext('p').findNext('p').a.text
  gross = movie.find('p',class_='sort-num_votes-visible').find_all('span')[-1].get_text()
  print(index,movie_name,rating,story,director,gross)

  thiller_movie_list.append({
      'Rank':index,
      'Name':movie_name,
      'Rate':rating,
      'Story':story,
      'Director':director,
      'Gross':gross,

  })

1 The Dark Knight 9 When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice. Christopher Nolan $534.86M
2 Mirror Game 9 Ayna, an alleged chef but a actor goes to jail for others. A political doppelganger threatens him to do time for him. Ayna faces death penalty. Journalist reveals his life. Ayna escapes acting as a jail guard. Amitabh Reza Chowdhury 29,062
3 Inception 8 A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster. Christopher Nolan $292.58M
4 Se7en 8 Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives. David Fincher $100.13M
5 The Silence of the Lambs 8 A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims. Jonathan Demme $130.74M
6 The Prestige 8 After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other. Christopher Nolan $53.09M
7 Parasite 8 Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan. Bong Joon Ho $53.37M
8 The Departed 8 An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston. Martin Scorsese $132.38M
9 Léon: The Professional 8 12-year-old Mathilda is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée and learns the assassin's trade. Luc Besson $19.50M
10 The Usual Suspects 8 The sole survivor of a pier shoot-out tells the story of how a notorious criminal influenced the events that began with five criminals meeting in a seemingly random police lineup. Bryan Singer $23.34M
11 Psycho 8 A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run and checks into a remote motel run by a young man under the domination of his mother. Alfred Hitchcock $32.00M
12 Rear Window 8 A photographer in a wheelchair spies on his neighbors from his Greenwich Village courtyard apartment window, and becomes convinced one of them has committed murder, despite the skepticism of his fashion-model girlfriend. Alfred Hitchcock $36.76M
13 The Dark Knight Rises 8 Eight years after the Joker's reign of chaos, Batman is coerced out of exile with the assistance of the mysterious Selina Kyle in order to defend Gotham City from the vicious guerrilla terrorist Bane. Christopher Nolan $448.14M
14 Joker 8 During the 1980's, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure. Todd Phillips $335.45M
15 Oldboy 8 After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days. Park Chan-wook $0.71M
16 Aliens 8 Decades after surviving the Nostromo incident, Ellen Ripley is sent out to re-establish contact with a terraforming colony but finds herself battling the Alien Queen and her offspring. James Cameron $85.16M
17 Memento 8 A man with short-term memory loss attempts to track down his wife's murderer. Christopher Nolan $25.54M
18 Come and See 8 After finding an old rifle, a young boy joins the Soviet resistance movement against ruthless German forces and experiences the horrors of World War II. Elem Klimov 89,876
19 The Lives of Others 8 In 1984 East Berlin, an agent of the secret police, conducting surveillance on a writer and his lover, finds himself becoming increasingly absorbed by their lives. Florian Henckel von Donnersmarck $11.29M
20 Witness for the Prosecution 8 A veteran British barrister must defend his client in a murder trial that has surprise after surprise. Billy Wilder $8.18M
21 High and Low 8 An executive of a Yokohama shoe company becomes a victim of extortion when his chauffeur's son is kidnapped by mistake and held for ransom. Akira Kurosawa 49,668
22 Kaithi 8 Dilli, an ex-convict, endeavours to meet his daughter for the first time after leaving prison. However, his attempts are interrupted due to a drug raid planned by Inspector Bejoy. Lokesh Kanagaraj 37,675
23 Drishyam 2 8 A gripping tale of an investigation and a family which is threatened by it. Will Georgekutty be able to protect his family this time? Jeethu Joseph 39,650
24 Reservoir Dogs 8 When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant. Quentin Tarantino $2.83M
25 Vertigo 8 A former San Francisco police detective juggles wrestling with his personal demons and becoming obsessed with the hauntingly beautiful woman he has been hired to trail, who may be deeply disturbed. Alfred Hitchcock $3.20M
26 North by Northwest 8 A New York City advertising executive goes on the run after being mistaken for a government agent by a group of foreign spies, and falls for a woman whose loyalties he begins to doubt. Alfred Hitchcock $13.28M
27 Vikram 8 A special investigator assigned a case of serial killings discovers the case is not what it seems to be, and leading down this path is only going to end in a war between everyone involved. Lokesh Kanagaraj 66,532
28 M 8 When the police in a German city are unable to catch a child-murderer, other criminals join in the manhunt. Fritz Lang $0.03M
29 Double Indemnity 8 A Los Angeles insurance representative lets an alluring housewife seduce him into a scheme of insurance fraud and murder that arouses the suspicion of his colleague, an insurance investigator. Billy Wilder $5.72M
30 K.G.F: Chapter 2 8 In the blood-soaked Kolar Gold Fields, Rocky's name strikes fear into his foes. While his allies look up to him, the government sees him as a threat to law and order. Rocky must battle threats from all sides for unchallenged supremacy. Prashanth Neel $6.60M
31 Kantara 8 When greed paves the way for betrayal, scheming and murder, a young tribal reluctantly dons the traditions of his ancestors to seek justice. Rishab Shetty 98,088
32 Raatchasan 8 A sub-inspector sets out in pursuit of a mysterious serial killer who targets teen school girls and murders them brutally. Ram Kumar 48,179
33 Drishyam 8 A man goes to extreme lengths to save his family from punishment after the family commits an accidental crime. Jeethu Joseph 43,054
34 Jurassic Park 8 A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose. Steven Spielberg $402.45M
35 No Country for Old Men 8 Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande. Ethan Coen $74.28M
36 Shutter Island 8 Teddy Daniels and Chuck Aule, two US marshals, are sent to an asylum on a remote island in order to investigate the disappearance of a patient, where Teddy uncovers a shocking truth about the place. Martin Scorsese $128.01M
37 Kill Bill: Vol. 1 8 After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her. Quentin Tarantino $70.10M
38 V for Vendetta 8 In a future British dystopian society, a shadowy freedom fighter, known only by the alias of "V", plots to overthrow the tyrannical government - with the help of a young woman. James McTeigue $70.51M
39 The Sixth Sense 8 Malcolm Crowe, a child psychologist, starts treating a young boy, Cole, who encounters dead people and convinces him to help them. In turn, Cole helps Malcolm reconcile with his estranged wife. M. Night Shyamalan $293.51M
40 Die Hard 8 A New York City police officer tries to save his estranged wife and several others taken hostage by terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles. John McTiernan $83.01M
41 L.A. Confidential 8 As corruption grows in 1950s Los Angeles, three policemen - one strait-laced, one brutal, and one sleazy - investigate a series of murders with their own brand of justice. Curtis Hanson $64.62M
42 Chinatown 8 A private detective hired to expose an adulterer in 1930s Los Angeles finds himself caught up in a web of deceit, corruption, and murder. Roman Polanski 339,841
43 The Secret in Their Eyes 8 A retired legal counselor writes a novel hoping to find closure for one of his past unresolved homicide cases and for his unreciprocated love with his superior - both of which still haunt him decades later. Juan José Campanella $6.39M
44 The Great Escape 8 Allied prisoners of war plan for several hundred of their number to escape from a German camp during World War II. John Sturges $12.10M
45 Tumbbad 8 A mythological story about a goddess who created the entire universe. The plot revolves around the consequences when humans build a temple for her first-born. Rahi Anil Barve 55,119
46 Demon Slayer the Movie: Mugen Train 8 After his family was brutally murdered and his sister turned into a demon, Tanjiro Kamado's journey as a demon slayer began. Tanjiro and his comrades embark on a new mission aboard the Mugen Train, on track to despair. Haruo Sotozaki $47.70M
47 Dial M for Murder 8 A former tennis star arranges the murder of his adulterous wife. Alfred Hitchcock $0.01M
48 Drishyam 2 8 A gripping tale of an investigation and a family which is threatened by it. Will Vijay Salgaonkar be able to protect his family this time? Abhishek Pathak 40,194
49 Gangs of Wasseypur 8 A clash between Sultan and Shahid Khan leads to the expulsion of Khan from Wasseypur, and ignites a deadly blood feud spanning three generations. Anurag Kashyap 100,758
50 The Wages of Fear 8 In a decrepit South American village, four men are hired to transport an urgent nitroglycerine shipment without the equipment that would make it safe. Henri-Georges Clouzot 64,364

In [39]:
Thiller = pd.DataFrame(thiller_movie_list)

In [40]:
Thiller

,Rank,Name,Rate,Story,Director,Gross
0,1,The Dark Knight,9,When the menace known as the Joker wreaks havo...,Christopher Nolan,$534.86M
1,2,Mirror Game,9,"Ayna, an alleged chef but a actor goes to jail...",Amitabh Reza Chowdhury,"29,062"
2,3,Inception,8,A thief who steals corporate secrets through t...,Christopher Nolan,$292.58M
3,4,Se7en,8,"Two detectives, a rookie and a veteran, hunt a...",David Fincher,$100.13M
4,5,The Silence of the Lambs,8,A young F.B.I. cadet must receive the help of ...,Jonathan Demme,$130.74M
5,6,The Prestige,8,"After a tragic accident, two stage magicians i...",Christopher Nolan,$53.09M
6,7,Parasite,8,Greed and class discrimination threaten the ne...,Bong Joon Ho,$53.37M
7,8,The Departed,8,An undercover cop and a mole in the police att...,Martin Scorsese,$132.38M
8,9,Léon: The Professional,8,12-year-old Mathilda is reluctantly taken in b...,Luc Besson,$19.50M
9,10,The Usual Suspects,8,The sole survivor of a pier shoot-out tells th...,Bryan Singer,$23.34M
10,11,Psycho,8,"A Phoenix secretary embezzles $40,000 from her...",Alfred Hitchcock,$32.00M
11,12,Rear Window,8,A photographer in a wheelchair spies on his ne...,Alfred Hitchcock,$36.76M
12,13,The Dark Knight Rises,8,"Eight years after the Joker's reign of chaos, ...",Christopher Nolan,$448.14M
13,14,Joker,8,"During the 1980's, a failed stand-up comedian ...",Todd Phillips,$335.45M
14,15,Oldboy,8,After being kidnapped and imprisoned for fifte...,Park Chan-wook,$0.71M
15,16,Aliens,8,"Decades after surviving the Nostromo incident,...",James Cameron,$85.16M
16,17,Memento,8,A man with short-term memory loss attempts to ...,Christopher Nolan,$25.54M
17,18,Come and See,8,"After finding an old rifle, a young boy joins ...",Elem Klimov,"89,876"
18,19,The Lives of Others,8,"In 1984 East Berlin, an agent of the secret po...",Florian Henckel von Donnersmarck,$11.29M
19,20,Witness for the Prosecution,8,A veteran British barrister must defend his cl...,Billy Wilder,$8.18M
20,21,High and Low,8,An executive of a Yokohama shoe company become...,Akira Kurosawa,"49,668"
21,22,Kaithi,8,"Dilli, an ex-convict, endeavours to meet his d...",Lokesh Kanagaraj,"37,675"
22,23,Drishyam 2,8,A gripping tale of an investigation and a fami...,Jeethu Joseph,"39,650"
23,24,Reservoir Dogs,8,When a simple jewelry heist goes horribly wron...,Quentin Tarantino,$2.83M
24,25,Vertigo,8,A former San Francisco police detective juggle...,Alfred Hitchcock,$3.20M
25,26,North by Northwest,8,A New York City advertising executive goes on ...,Alfred Hitchcock,$13.28M
26,27,Vikram,8,A special investigator assigned a case of seri...,Lokesh Kanagaraj,"66,532"
27,28,M,8,When the police in a German city are unable to...,Fritz Lang,$0.03M
28,29,Double Indemnity,8,A Los Angeles insurance representative lets an...,Billy Wilder,$5.72M
29,30,K.G.F: Chapter 2,8,"In the blood-soaked Kolar Gold Fields, Rocky's...",Prashanth Neel,$6.60M
30,31,Kantara,8,"When greed paves the way for betrayal, schemin...",Rishab Shetty,"98,088"
31,32,Raatchasan,8,A sub-inspector sets out in pursuit of a myste...,Ram Kumar,"48,179"
32,33,Drishyam,8,A man goes to extreme lengths to save his fami...,Jeethu Joseph,"43,054"
33,34,Jurassic Park,8,A pragmatic paleontologist touring an almost c...,Steven Spielberg,$402.45M
34,35,No Country for Old Men,8,Violence and mayhem ensue after a hunter stumb...,Ethan Coen,$74.28M
35,36,Shutter Island,8,"Teddy Daniels and Chuck Aule, two US marshals,...",Martin Scorsese,$128.01M
36,37,Kill Bill: Vol. 1,8,"After awakening from a four-year coma, a forme...",Quentin Tarantino,$70.10M
37,38,V for Vendetta,8,"In a future British dystopian society, a shado...",James McTeigue,$70.51M
38,39,The Sixth Sense,8,"Malcolm Crowe, a child psychologist, starts tr...",M. Night Shyamalan,$293.51M
39,40,Die Hard,8,A New York City police officer tries to save h...,John McTiernan,$83.01M
40,41,L.A. Confidential,8,"As corruption grows in 1950s Los Angeles, thre...",Curtis Hanson,$64.62M
41,42,Chinatown,8,A private detective hired to expose an adulter...,Roman Polanski,"339,841"
42,43,The Secret in Their Eyes,8,A retired legal counselor writes a novel hopin...,Juan José Campanella,$6.39M
43,44,The Great Escape,8,Allied prisoners of war plan for several hundr...,John Sturges,$12.10M
44,45,Tumbbad,8,A mythological story about a goddess who creat...,Rahi Anil Barve,"55,119"
45,46,Demon Slayer the Movie: Mugen Train,8,After his family was brutally murdered and his...,Haruo Sotozaki,$47.70M
46,47,Dial M for Murder,8,A former tennis star arranges the murder of hi...,Alfred Hitchcock,$0.01M
47,48,Drishyam 2,8,A gripping tale of an investigation and a fami...,Abhishek Pathak,"40,194"
48,49,Gangs of Wasseypur,8,A clash between Sultan and Shahid Khan leads t...,Anurag Kashyap,"100,758"
49,50,The Wages of Fear,8,"In a decrepit South American village, four men...",Henri-Georges Clouzot,"64,364"

In [42]:
Thiller['Story'][15]

'Decades after surviving the Nostromo incident, Ellen Ripley is sent out to re-establish contact with a terraforming colony but finds herself battling the Alien Queen and her offspring.'